### ISSUE TITLE
How to disable the 3d in map

### ISSUE THREAD

**Issue by skylning** [geopaparazzi/geopaparazzi#653] opened 2020-05-09 15:49 UTC
I want to set the mapview  to 2d,how to do it?i read the source code and i can't found anywhere to disbale the 3d,thanks

**Comment by moovida** [comment] 2020-05-09 16:50
You can block the map from rotating and tilting with this: https://github.com/geopaparazzi/geopaparazzi/blob/master/geopaparazzi_map/src/main/java/eu/geopaparazzi/map/GPMapView.java#L295

This is what is necessary for all the editing tools to work properly.

If you happen to fix the editing issue, a Pull Request is always welcome.

**Comment by skylning** [comment] 2020-05-10 11:43
thanks for your replay.
Yes,I block the map from rotating and tilting by call the block map and update the releaseMapBlock to call block map,and i call the blockmap on GPMapView constract,but i can not fix the edit features bug ,enven ,i reset the map roll ,the editing tools bug is happen.
and i noticed that the source code have call the blockmap method when actived editing tools,and called the releasemapblock when finished the editing operation

**Comment by moovida** [comment] 2020-05-26 05:43
Sorry for the late reply @skylning , I am looking into this right now. If you can give a workflow to reproduce this, it would help.

**Comment by moovida** [comment] 2020-05-26 05:55
Hi @skylning I did two tests with polygon creation, one with the tap of fingers:
![image](https://user-images.githubusercontent.com/390250/82864934-f1f20d80-9f25-11ea-9b00-545a91e98683.png)

and one with the adding by center cross:
![image](https://user-images.githubusercontent.com/390250/82864962-00d8c000-9f26-11ea-905e-84ec87548efe.png)

and things look good. No offset, no issues. Also, when editing starts, the map is put in 2D mode, so there no problem with the 3D situation.

Do you have your own custom version of the app or are you using geopaparazzi directly? I am not able to reproduce your issues.

**Comment by skylning** [comment] 2020-05-29 03:01
Thanks your reply!before  darw a polygon or polyline geometry, i zoomed or rotated the mapview  use two finger ,then save the geometry ,the save result is wrong such as the issue #652 description

**Comment by moovida** [comment] 2020-05-29 05:27
@skylning , I have finally been able to reproduce the error, though I have not a well defined workflow yet. Even if I am not sure why it is happening, I will definitely look into it. Thanks

**Comment by moovida** [comment] 2020-08-20 10:15
Due to missing tie and resources, this is currently fixed by adding a way to disable 3D.

**Closed by moovida** 2020-08-20 10:15 UTC
Labels: bug
