### ISSUE TITLE
Openandromaps mapsforge map not working.

### ISSUE THREAD

**Issue by RW-gis** [geopaparazzi/geopaparazzi#327] opened 2016-05-31 10:25 UTC
I set Geopaparazzi up to use an Openandromaps map for the first time a week or two ago. This worked fine. Then a few days ago it stopped working. I've tested this on a separate device (Samsung Galaxy Tab tablet vs Moto G android smartphone) with a new installation of Geopaparazzi and the Openandromaps map. It failed on the new installation too. 

The Openandromaps map is installed in a subfolder of the Oruxmaps folder on my device, with a mapsforge style (xml file) with the same name in the same folder.

I'm using the version of Geopaparazzi from Google Play.

**Comment by moovida** [comment] 2016-05-31 10:52
Outch, I was wondering if that would ever happen. Is it possible that the styles changed? I think there were problems with internal references to the connected image files. 

I am not able to check now, but am sure interested to have that working, since those maps are great. 

Can you try the maps removing the style folder? It should appear similar to the "normal" map files. If that works, then it is indeed the styles files. In which case we could adapt them to work with geopap and make them available for everyone here?

**Comment by RW-gis** [comment] 2016-05-31 15:00
Tested this. Removing the style xml file makes the map visible again - so it is the map style files which are not working.

To test this I changed the style file name so that it did not match the Openandromaps .map file name. The map became visible. I changed the name so that it did match the .map file name. The map vanished. I changed the name again, and added a new different style file with a filename which matched the .map file name. The map vanished. I changed the name of the map style file and the map reappeared. During this process I did a full exit of Geopaparazzi often. 

These are map style files (.xml) which I use currently in Oruxmaps. I tested them again today and they are working in Oruxmaps. I believe that previously they were working in Geopaparazzi too, but I didn't use Geopaparazzi properly yet so I may be mistaken.

**Comment by moovida** [comment] 2016-05-31 16:47
Yes, it is the themes that changed at some point I think. And Oruxmaps resolved some internal paths differently than mapsforge (on which geopap is based) does. I now remember I adapted the first changed version of the tiramisu theme and placed it here:

https://drive.google.com/open?id=0B3mhEzI1NTTbb18xYVVUOFUxamc

I was planning to do so with each new release, but then had no time and it all faded...

I don't remember right now, but I am quite sure the trick lies all in the path to the images. Some thing like changing **file:/** into **./**. But I will have to check. If you happen to have a look, please let me know, so I document it. I will try to find some time also in the next days.

**Comment by MB1965** [comment] 2016-11-06 16:27
I have another problem with Openandromaps maps. The current versions of the maps don't work anymore with Geopaparazzi. There is a strange behaviour: some tiles load correctly, also over several zoom levels while others stay gray.

I don't use a style file, just the internal render theme.

![patchy](https://cloud.githubusercontent.com/assets/22999651/20039467/be69f912-a444-11e6-9f9a-e3b8ceddf41c.jpg)

I first noticed this in September 2016 and it seems that the problem remains. I tested with several maps from Europe, which I downloaded from here: http://www.openandromaps.org/en/downloads/europe.

I suppose it has something to do with the style theme. Maybe on some tiles there are icons or items that are not compatible anymore with the internal rendertheme (these tiles stay gray), while on other tiles there are none of these (so they load)?

It's probably a lot of work, but it would be really nice to upgrade to mapsforge version 0.6. I believe that this problem will go away then and we could also use the modern Elevate theme.

**Comment by RW-gis** [comment] 2016-11-07 16:33
Looking at the adapted style that you link to @moovida , and comparing this to two I have on my phone for use with Oruxmaps, I can see the following:

Excerpt from your adapted tiramisu style:
`<area src="file:./Tiramisu/p_wood-mixed.png" />`
or 
`<symbol src="file:./Tiramisu/s_via_ferrata.png" />`

Whereas in my copy of the Elements.xml file I have:
`<area src="file:ele_res/p_wood-coniferous.png" />`
and 
`<area src="file:ele_res/p_cemetery.png" stroke="#E4E4E4" stroke-width="0.15" />`

And in my copy of the Elevate.xml style file something similar:
`<area src="file:ele_res/p_wood-coniferous.png" />`
and
`<area src="file:ele_res/p_pedestrian.png" />` 

This suggests that you may be correct in that after the word "file:" there is an extra 
`./`
I may try to adapt one of my styles myself to see if this solves the problem.

**Comment by RW-gis** [comment] 2016-11-07 17:52
OK - this works - I have a working map. I'm not sure if the problem was the missing "./" in the file references or the fact that I hadn't changed the file references to match the locations of the map symbols. I hadn't entirely appreciated that the style files referenced symbols which I'd not moved from their original location.

Here's what people need to know - I suggest the following addition to this section of this page: [http://geopaparazzi.github.io/geopaparazzi/maps.html#apply-a-render-theme](http://geopaparazzi.github.io/geopaparazzi/maps.html#apply-a-render-theme) 

Apply a render theme
When rendering mapforge tiles locally Geopaparazzi is able to apply a render theme. The theme xml file needs to have the same name as the map file and to be in the same folder as the map file. For example  the above cycle map example has a map:
italy_cycle.map
and a render theme:
italy_cycle.xml
which in the same folder as the map file.
Note that Mapsforge render theme xml files contain references to the symbols which are used on the map. You need to ensure that file references in the xml file are to the correct location for where the symbols are stored (this may be a problem if copying render themes from elsewhere). For example you may need to use find & replace to change lines in the file like:
file:ele_res/p_wood-mixed.png
to be lines like this
file:../../mapstyles/ele_res/p_wood-mixed.png
or 
file:./ele_res/p_wood-mixed.png
Note the "./" may be important (some styles omit this). It means start in this folder and work downward - whereas "../" means go up a folder level or "../../" means go up two folder levels

**Comment by MB1965** [comment] 2016-11-07 20:19
@RW-gis
I am not sure if I understood you correctly.

I tried the Tiramisu_HR style from the link above, together with a map from Openandromaps (from 05.11.2016), and while I could see on the water and coast tiles that were loaded correctly, that the Tiramisu style was in use, most land tiles were not rendered. The xml file was renamed like the map and put in the mapsfolder.

I also tried to replace "file:./Tiramisu_HR" with "file:Tiramisu_HR", but the result was the same.

Can you please upload your working xml file with png folder, that is confirmed to work with current Openandromaps maps, so I can try it on my device?

**Comment by moovida** [comment] 2016-11-08 04:30
@RW-gis sorry to chime in late, I confirm that at some point the changes in mapsforge/tiramisu there required the above change you mention. At the veri begin I made the theme available here: https://drive.google.com/open?id=1NFxfzQXg98kZmkjovrKrjv9YVpwbL2xiSD_5aszK9zU
But then was not able to maintain it.

It would be nice to share the complete theme, we could put it somewhere to download. We could even create under the geopaparazzi umbrella a theme project, in which we place the working ones.

**Comment by MB1965** [comment] 2017-02-12 17:17
Any news here?

The maps from http://www.openandromaps.org/en/downloads/europe don't work with Geopaparazzi anymore.
The maps from http://download.mapsforge.org/maps/europe work.

This does not seem to be a problem of the rendertheme, but rather an incompatibility of the OAM mapfiles and the mapsforge version used in Geopaparazzi. 

Or maybe a problem of resources (cache size, ...) due to more details in the OAM maps?

@moovida Do you plan to update the mapsforge version, which is at 0.7.0 now (while Geopaparazzi is still on 0.3.0 from 2014 I believe)? This would probably solve this issue and also support the modern Elevate themes.

**Comment by moovida** [comment] 2017-02-14 08:54
This comes in timely, I just wrote a post about possible updates right here: 
http://jgrasstechtips.blogspot.it/2017/02/wrap-up-of-geopaparazzi-code-sprint-in.html

At the moment an upgrade is difficult to support, being lots of work.

**Comment by gvghia** [comment] 2017-04-26 09:53
As [parts of the map are not showed](https://github.com/geopaparazzi/geopaparazzi/issues/327#issuecomment-258692011), this is due to an error during generating and applying the style xml of that location.
Is there a way to inspect some error log in order to find and easier fix the problems?

In the style file I was using, are references like:
jar:/org/mapsforge/android/maps/rendertheme/osmarender/patterns/military.png
Where are they pointing to?
Is there somewhere a list of the available icons? (Was trying to add wayside shrine)

If there is no xml file with the .map file, there is some default style used.
Where is this located? 
(I have some andro maps who don't work without dedicated style file either and generate only a few tiles on some scales)

Other problem with some downloaded maps is that they have not good naming inside and show all the same. One solution should be to display the filename in the map selection menu.

Also it is not easy to see which map is actually selected.

**Comment by moovida** [comment] 2017-06-09 08:07
We are now finding a solution to this problem. 
Updating in issue #406 and closing here.

**Closed by moovida** 2017-06-09 08:07 UTC
Labels: bug
