### ISSUE TITLE
Version 5.0.0 and 5.0.1 not working for me

### ISSUE THREAD

**Issue by mj10777** [geopaparazzi/geopaparazzi#315] opened 2016-04-21 11:32 UTC
At least for my version of android
* none of my
   * RasterLite (with the RL2-Libs)
   * Geometries can be opened

I can see and load the mbtiles, map and mapurl files
* but nothing is listed for `.db` files
   * for both Raster and Vector dialog's

I have also saw that the Directory are sorted strangely
* Capital Letters first, then smaller letters in the directory name
   * `maps` being very far down the list

Also when recalling the Directory dialog's
* it does not remember the last used position
   * so you must start from root again

---
A scan Directory function should be (re)introduced
* to be called when desired
   * useful when a large amount of maps exist

**Comment by moovida** [comment] 2016-04-26 15:06
I had in mind to add a load folder as soon as I have time for it. Maybe by long-touching the plus sign.

About the missing db extension, that should be easy to fix.

About the directory order, I will have to check, I didn't notice that.

**Comment by mj10777** [comment] 2016-05-02 07:53
I have looked to see if I could resolve the `db extension` problem
* since at the moment I have no RL2.Maps or geometries
   * but found nothing obvious (the calling of `SpatialiteDatabaseType` has not changed) 

So I assume this is now done elsewhere.

Since I will be preparing a new driver version
* where `LWGEOM` will be replaced
   * https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/spatialite-users/MlXsPU0ZMYw

I would like to a working version

**Comment by mj10777** [comment] 2016-05-06 13:10
I have, in the meantime, found the 2 places to make these changes
* class SourcesTreeListActivity
* class SpatialiteDatabasesTreeListActivity

After-which I tried again
* using my version of the Database-driver with Rasterlite2 support

---
A quick and dirty summery:

---

The maps loaded and showed
* the geometries did not

This, it seems, is caused by multiple errors

But first:
* when loading the found Tables/Views
   * the list is not sorted
   * all tables/views are set to active
      * this caused the first error

An very old view, that I have not used in a long time
* did not have the PK defined and thus failed
   * since all of the tables were active
   * when the first fails, no attempt is made to render others

So I corrected the database and started again
* copying over the newer version of the database

Geopaparazzi complained that it could not find the styles table
* so I removed the database from the list and reloaded it (after a restart)

Could again received a list
* changed a style (adding a label)
   * still nothing showed

The log-book showed now a different error
* `to many connections` (> 64) 

At this point there should only be 2 connections
* 1 the RasterLite2 map being shown
* the Database with 97 Table/Views

---
After further *playing* around
* attempting to only load the (4) tables
   * still no results
* after reactivating the views
   * again `to many connections`
      * only a reboot resolves this
         * not a restart

---
I also noted, that when loading the Geometries from the RasterLite2 Database
* the RL2-Admin Tables (that contain Geometries) are being shown
   * which should not happen

---
The new placement of the log-book is nice
* it would be nice if one could send the shown as an attachment to an e-mail account
   * I wanted to test the shown sql to figure out that portion of the problem

**Comment by moovida** [comment] 2016-05-16 03:50
Hi @mj10777 , I will look into this as soon as possible. Thanks

**Comment by moovida** [comment] 2016-05-25 19:43
Hi @mj10777 I am trying to figure out the problems you are having but am not able to reproduce.

I fixed at least the db extension you need for now.

Can you break down the problems in different issues with a workflow to reproduce them. 

I would like to solve them. I can't understand why you get too many connections.

For now I close this here, let's open new, smaller issues.

**Closed by moovida** 2016-05-25 19:43 UTC
Labels: bug
