### ISSUE TITLE
SD card directory

### ISSUE THREAD

**Issue by GeoHigh125** [geopaparazzi/geopaparazzi#533] opened 2018-06-24 12:01 UTC
Until  version 5.5.0 we had a possibility the set an own path on the SD.  In version 5.6.0. this is missing.
Is there a possibility to get this back ?

**Comment by GeoHigh125** [comment] 2018-06-25 15:40
Hi ,

I only missed it in the new version and it was mentioned in the gvSIG video
explanation.
They used it to store files uploading to the device.

Further I was hoping that I could use it for a fixed location for the
generated PDF files. They are now stored at the root of the emulated SD
card.
I can not synchronize automatically from that location because the
synctoolapp will sync all files and folders. I want only copy the generated
KMZ, PDF, GPS and the images from one project.
Would it be possible to use the projectfolder ?

Cheers
Peter




Op ma 25 jun. 2018 14:25 schreef Andrea Antonello <notifications@github.com

**Comment by moovida** [comment] 2018-06-27 11:40
Yes, I agree that all the files exported should land in the same place. An export folder inside the geopaparazzi folder should be good.

**Comment by moovida** [comment] 2018-06-27 11:44
This is kind of a duplicate of issue #524
Closing this here, discussin there

**Closed by moovida** 2018-06-27 11:44 UTC
